"""
Jupiter execution layer.

KEY CUSTODY, stated plainly: the signing key is read from the environment of
YOUR server. It is generated by you, funded by you, and never leaves that box.
Nobody else — including whoever helped build this — ever sees it.

Use a DEDICATED hot wallet funded only with the trading allocation. Never the
wallet holding the rest of your money. A trading bot's key is a hot key by
definition and should be treated as spendable-at-risk.
"""
from __future__ import annotations
import base64
import os
from dataclasses import dataclass
import requests

LITE = "https://lite-api.jup.ag/swap/v1"
PRO = "https://api.jup.ag/swap/v1"
SOL_MINT = "So11111111111111111111111111111111111111112"
LAMPORTS = 1_000_000_000


@dataclass
class Quote:
    in_mint: str
    out_mint: str
    in_amount: int
    out_amount: int
    price_impact_pct: float
    slippage_bps: int
    raw: dict

    @property
    def price_impact(self) -> float:
        return self.price_impact_pct * 100.0


class ExecutionError(RuntimeError):
    pass


class JupiterExecutor:
    def __init__(self, rpc_url: str | None = None, api_key: str | None = None,
                 dry_run: bool = True, timeout: int = 25):
        self.base = PRO if api_key else LITE
        self.api_key = api_key
        self.rpc = rpc_url or os.environ.get(
            "SOLANA_RPC_URL", "https://api.mainnet-beta.solana.com")
        self.dry_run = dry_run
        self.timeout = timeout
        self.s = requests.Session()
        if api_key:
            self.s.headers.update({"x-api-key": api_key})
        self._kp = None

    # -- key handling ---------------------------------------------------
    @property
    def keypair(self):
        """Loaded lazily and only when actually needed to sign."""
        if self._kp is None:
            import base58
            from solders.keypair import Keypair
            raw = os.environ.get("SOLANA_PRIVATE_KEY", "").strip()
            if not raw:
                raise ExecutionError(
                    "SOLANA_PRIVATE_KEY not set. Generate a dedicated hot wallet "
                    "and put its base58 secret key in your .env — never your main wallet.")
            self._kp = Keypair.from_bytes(base58.b58decode(raw))
        return self._kp

    @property
    def pubkey(self) -> str:
        return str(self.keypair.pubkey())

    # -- quoting --------------------------------------------------------
    def quote(self, in_mint: str, out_mint: str, amount: int,
              slippage_bps: int = 100) -> Quote:
        r = self.s.get(f"{self.base}/quote", timeout=self.timeout, params={
            "inputMint": in_mint, "outputMint": out_mint,
            "amount": int(amount), "slippageBps": int(slippage_bps),
            "restrictIntermediateTokens": "true"})
        if r.status_code != 200:
            raise ExecutionError(f"quote failed {r.status_code}: {r.text[:180]}")
        d = r.json()
        try:
            return Quote(in_mint, out_mint, int(d["inAmount"]), int(d["outAmount"]),
                         float(d.get("priceImpactPct") or 0.0), int(d.get("slippageBps", slippage_bps)), d)
        except (KeyError, TypeError, ValueError) as e:
            raise ExecutionError(f"malformed quote: {e}")

    # -- the safety gate on every single swap ----------------------------
    def check_quote(self, q: Quote, max_impact_pct: float,
                    min_out: int | None = None) -> list[str]:
        """Last line of defence, evaluated against the LIVE quote, not an estimate."""
        problems = []
        if q.price_impact > max_impact_pct:
            problems.append(f"price_impact {q.price_impact:.2f}% > {max_impact_pct:.2f}% cap")
        if min_out is not None and q.out_amount < min_out:
            problems.append(f"out_amount {q.out_amount} below floor {min_out}")
        if q.out_amount <= 0:
            problems.append("zero output — no route")
        return problems

    # -- swapping -------------------------------------------------------
    def build_swap(self, q: Quote, user_pubkey: str,
                   priority_lamports: int = 100_000) -> str:
        body = {
            "quoteResponse": q.raw,
            "userPublicKey": user_pubkey,
            "wrapAndUnwrapSol": True,
            "dynamicComputeUnitLimit": True,
            "prioritizationFeeLamports": {
                "priorityLevelWithMaxLamports": {
                    "maxLamports": int(priority_lamports),
                    "priorityLevel": "high"}},
        }
        r = self.s.post(f"{self.base}/swap", json=body, timeout=self.timeout)
        if r.status_code != 200:
            raise ExecutionError(f"swap build failed {r.status_code}: {r.text[:180]}")
        tx = r.json().get("swapTransaction")
        if not tx:
            raise ExecutionError("no swapTransaction in response")
        return tx

    def sign_and_send(self, swap_tx_b64: str) -> str:
        if self.dry_run:
            return "DRY_RUN_NOT_SENT"
        from solders.transaction import VersionedTransaction
        from solders.message import to_bytes_versioned
        # Any parsing/signing failure must surface as ExecutionError. A raw
        # ValueError escaping here would bypass the service's error handling
        # and could leave a proposal in limbo instead of cleanly failed.
        try:
            raw = VersionedTransaction.from_bytes(base64.b64decode(swap_tx_b64))
            sig = self.keypair.sign_message(to_bytes_versioned(raw.message))
            signed = VersionedTransaction.populate(raw.message, [sig])
            payload = base64.b64encode(bytes(signed)).decode()
        except ExecutionError:
            raise
        except Exception as e:
            raise ExecutionError(f"could not parse/sign swap transaction: {type(e).__name__}: {e}")
        r = self.s.post(self.rpc, timeout=self.timeout, json={
            "jsonrpc": "2.0", "id": 1, "method": "sendTransaction",
            "params": [payload, {"encoding": "base64", "skipPreflight": False,
                                 "maxRetries": 3, "preflightCommitment": "confirmed"}]})
        d = r.json()
        if "error" in d:
            raise ExecutionError(f"send failed: {str(d['error'])[:200]}")
        return d.get("result", "")

    def confirm(self, signature: str, tries: int = 20, delay: float = 2.0) -> bool:
        """A swap is not done until the chain says so. Never assume a send landed."""
        import time
        if self.dry_run or not signature or signature == "DRY_RUN_NOT_SENT":
            return True
        for _ in range(tries):
            r = self.s.post(self.rpc, timeout=self.timeout, json={
                "jsonrpc": "2.0", "id": 1, "method": "getSignatureStatuses",
                "params": [[signature], {"searchTransactionHistory": True}]})
            try:
                st = (r.json().get("result", {}).get("value") or [None])[0]
            except Exception:
                st = None
            if st:
                if st.get("err"):
                    return False
                if st.get("confirmationStatus") in ("confirmed", "finalized"):
                    return True
            time.sleep(delay)
        return False

    def swap(self, in_mint: str, out_mint: str, amount: int, slippage_bps: int,
             max_impact_pct: float) -> dict:
        """Full path with the live-quote gate enforced before anything is signed."""
        q = self.quote(in_mint, out_mint, amount, slippage_bps)
        problems = self.check_quote(q, max_impact_pct)
        if problems:
            return {"ok": False, "stage": "quote_gate", "problems": problems,
                    "price_impact_pct": q.price_impact}
        tx = self.build_swap(q, self.pubkey)
        sig = self.sign_and_send(tx)
        landed = self.confirm(sig)
        return {"ok": landed, "stage": "sent" if landed else "not_confirmed",
                "signature": sig, "in_amount": q.in_amount, "out_amount": q.out_amount,
                "price_impact_pct": q.price_impact, "dry_run": self.dry_run}
